[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "mpl-utils"
requires-python = ">=3.8"
dependencies = [
    "matplotlib>=3.5"
]
dynamic = ["version"]

[tool.setuptools_scm]

